const newTopics = [
    {
        avatar: "",
        tag: "Help",
        title: "Thesis Title Recommendation",
        user: "Benjie S",
        date: "Feb 20, 2025",
        category: "Academics",
        replies: 15,
        views: 102,
        time: "2:11 AM",
        lastAvatar: "https://i.pravatar.cc/40?img=2",
      },
      {
        avatar: "https://i.pravatar.cc/40?img=3",
        tag: "Tips",
        title: "Study Hacks",
        user: "Benjack",
        date: "Feb 20, 2025",
        category: "Academics",
        replies: 10,
        views: 19,
        time: "1:31 AM",
        lastAvatar: "https://i.pravatar.cc/40?img=4",
      },
      {
        avatar: "https://i.pravatar.cc/40?img=5",
        tag: "Rant",
        title: "Dirty Restroom :(",
        user: "Kak",
        date: "Feb 20, 2025",
        category: "Vent",
        replies: 20,
        views: 100,
        time: "12:51 AM",
        lastAvatar: "https://i.pravatar.cc/40?img=6",
      },
      {
        avatar: "https://i.pravatar.cc/40?img=7",
        tag: "Info",
        title: "VSU New Course!!",
        user: "IDK123",
        date: "Feb 20, 2025",
        category: "University",
        replies: 1,
        views: 14,
        time: "10:13 AM",
        lastAvatar: "https://i.pravatar.cc/40?img=8",
      },
      {
        avatar: "https://i.pravatar.cc/40?img=9",
        tag: "Help",
        title: "Lost Wallet",
        user: "Lizardy",
        date: "Feb 20, 2025",
        category: "Lost and Found",
        replies: 0,
        views: 46,
        time: "Yesterday",
        lastAvatar: "https://i.pravatar.cc/40?img=10",
      },
      {
        avatar: "https://i.pravatar.cc/40?img=9",
        tag: "Help",
        title: "Lost Wallet",
        user: "Lizardy",
        date: "Feb 20, 2025",
        category: "Lost and Found",
        replies: 0,
        views: 46,
        time: "Yesterday",
        lastAvatar: "https://i.pravatar.cc/40?img=10",
      },
      {
        avatar: "https://i.pravatar.cc/40?img=9",
        tag: "Help",
        title: "Lost Wallet",
        user: "Lizardy",
        date: "Feb 20, 2025",
        category: "Lost and Found",
        replies: 0,
        views: 46,
        time: "Yesterday",
        lastAvatar: "https://i.pravatar.cc/40?img=10",
      },
      {
        avatar: "https://i.pravatar.cc/40?img=9",
        tag: "Help",
        title: "Lost Wallet",
        user: "Lizardy",
        date: "Feb 20, 2025",
        category: "Lost and Found",
        replies: 0,
        views: 46,
        time: "Yesterday",
        lastAvatar: "https://i.pravatar.cc/40?img=10",
      },
      {
        avatar: "https://i.pravatar.cc/40?img=7",
        tag: "Info",
        title: "VSU New Course!!",
        user: "IDK123",
        date: "Feb 20, 2025",
        category: "University",
        replies: 1,
        views: 14,
        time: "10:13 AM",
        lastAvatar: "https://i.pravatar.cc/40?img=8",
      },
];

export default newTopics;